In [107]:
using LinearAlgebra

# Sua matriz A
A = [-3 -6; 0 2; 4 8;]

# Realiza a decomposição QR
Q, R = qr(A)

# Q é a matriz ortogonal, R é a matriz triangular superior


LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor:
3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}:
 -0.6  0.0  0.8
  0.0  1.0  0.0
  0.8  0.0  0.6
R factor:
2×2 Matrix{Float64}:
 5.0  10.0
 0.0   2.0

In [99]:
using LinearAlgebra

In [100]:
function GS_MOD(A)
    m, n = size(A)
    Q = zeros(m, n)
    R = zeros(n, n)

    kValues = []
    print("Para k = ")
    for k = 1:n
        print(k, " ")
    end

    print("faça\n")


    for k = 1:n
        print("\tPara k = $k faça:\n")
        v = A[:, k]
        print("\t\tu
k) => ", v, "\n")
        for j = 1:k-1
            print("\t\tPara j = $j faça:\n")
            print("\t\t\tR[
k] = w
k => ", dot(Q[:, j], A[:, k]), "\n")
            R[j, k] = dot(Q[:, j], A[:, k])
            print("\t\t\tu
k - R[
k]*w$j => ", v - R[j, k]*Q[:, j], "\n")
            v = v - R[j, k]*Q[:, j]
        end
        print("\t\tr[
k] = norm(u$k) => ", norm(v), "\n")
        print("\t\tw
k/r[
k] => ", v/norm(v), "\n") # Q[:, k] = v/R[k, k
        R[k, k] = norm(v)
        Q[:, k] = v/R[k, k]
        print("\n")
    end
    return Q, R
end

GS_MOD (generic function with 1 method)

In [102]:
A = [1 -1 0; -1 1 0; 0 0 -1;];

Q, R = GS_MOD(A);

println("Q = ", Q)
println("R = ", R)
Q * R

Para k = 1 2 3 faça
	Para k = 1 faça:
		u
k) => [1, -1, 0]
		r[
k] = norm(u1) => 1.4142135623730951
		w
k/r[
k] => [0.7071067811865475, -0.7071067811865475, 0.0]

	Para k = 2 faça:
		u
k) => [-1, 1, 0]
		Para j = 1 faça:
			R[
k] = w
k => -1.414213562373095
			u
k - R[
k]*w1 => [-2.220446049250313e-16, 2.220446049250313e-16, 0.0]
		r[
k] = norm(u2) => 3.1401849173675503e-16
		w
k/r[
k] => [-0.7071067811865475, 0.7071067811865475, 0.0]

	Para k = 3 faça:
		u
k) => [0, 0, -1]
		Para j = 1 faça:
			R[
k] = w
k => 0.0
			u
k - R[
k]*w1 => [0.0, 0.0, -1.0]
		Para j = 2 faça:
			R[
k] = w
k => 0.0
			u
k - R[
k]*w2 => [0.0, 0.0, -1.0]
		r[
k] = norm(u3) => 1.0
		w
k/r[
k] => [0.0, 0.0, -1.0]

Q = [0.7071067811865475 -0.7071067811865475 0.0; -0.7071067811865475 0.7071067811865475 0.0; 0.0 0.0 -1.0]
R = [1.4142135623730951 -1.414213562373095 0.0; 0.0 3.1401849173675503e-16 0.0; 0.0 0.0 1.0]


3×3 Matrix{Float64}:
  1.0  -1.0   0.0
 -1.0   1.0   0.0
  0.0   0.0  -1.0

In [ ]:
[-3]

In [106]:
A = [-3 0 4; -6 2 8;]

Q, R = GS_MOD(A);

println("Q = ", Q)
println("R = ", R)
Q * R

Para k = 1 2 3 faça
	Para k = 1 faça:
		u
k) => [-3, -6]
		r[
k] = norm(u1) => 6.708203932499369
		w
k/r[
k] => [-0.4472135954999579, -0.8944271909999159]

	Para k = 2 faça:
		u
k) => [0, 2]
		Para j = 1 faça:
			R[
k] = w
k => -1.7888543819998317
			u
k - R[
k]*w1 => [-0.7999999999999999, 0.40000000000000013]
		r[
k] = norm(u2) => 0.8944271909999159
		w
k/r[
k] => [-0.8944271909999159, 0.4472135954999581]

	Para k = 3 faça:
		u
k) => [4, 8]
		Para j = 1 faça:
			R[
k] = w
k => -8.94427190999916
			u
k - R[
k]*w1 => [0.0, 0.0]
		Para j = 2 faça:
			R[
k] = w
k => 1.3322676295501878e-15
			u
k - R[
k]*w2 => [1.191616393558691e-15, -5.958081967793457e-16]
		r[
k] = norm(u3) => 1.332267629550188e-15
		w
k/r[
k] => [0.8944271909999157, -0.44721359549995804]

Q = [-0.4472135954999579 -0.8944271909999159 0.8944271909999157; -0.8944271909999159 0.4472135954999581 -0.44721359549995804]
R = [6.708203932499369 -1.7888543819998317 -8.94427190999916; 0.0 0.8944271909999159 1.3322676295501878e-15; 

2×3 Matrix{Float64}:
 -3.0  -2.51898e-17  4.0
 -6.0   2.0          8.0

### QR Reduzido

In [87]:
A = [2 0; -1 0;0 -1;]

3×2 Matrix{Int64}:
  2   0
 -1   0
  0  -1

In [36]:
A1 = A;

x = A1[:,1]
e1 = [1 ; 0 ;0];
α1 = round.(norm(x),digits = 6);
v = round.(x - α1*e1,digits=6);

u = v / norm(v)

3-element Vector{Float64}:
 -0.22975294128973506
 -0.9732489845711196
  0.0

In [37]:
u = round.(u,digits=6)

3-element Vector{Float64}:
 -0.229753
 -0.973249
  0.0

In [38]:
Q1 = diagm(ones(3)) - 2*u*u'

3×3 Matrix{Float64}:
  0.894427  -0.447214  0.0
 -0.447214  -0.894427  0.0
  0.0        0.0       1.0

In [39]:

A2 = round.(Q1*A1, digits = 6)
#A2til = A2[2:end,2:end]

3×2 Matrix{Float64}:
  2.23607   0.0
 -0.0       0.0
  0.0      -1.0

In [111]:
A2 = Q1*A1

3×2 Matrix{Float64}:
  2.23607      0.0
 -2.77986e-7   0.0
  0.0         -1.0

In [112]:
A2til = A2[2:end,2:end]

2×1 Matrix{Float64}:
  0.0
 -1.0

In [113]:
x = A2til[:,1]
e1 = [1 ; 0;];
α2 = norm(x)


1.0

In [114]:
v = x - α2*e1;

u = v / norm(v);

In [115]:
round.(u,digits=6)

2-element Vector{Float64}:
 -0.707107
 -0.707107

In [116]:
Q2til = diagm(ones(2))-2*u*u'

2×2 Matrix{Float64}:
  2.22045e-16  -1.0
 -1.0           2.22045e-16

In [117]:
Q2 = [1 0 0; 0 0 -1; 0 -1 0;]

3×3 Matrix{Int64}:
 1   0   0
 0   0  -1
 0  -1   0

In [51]:
A3 = round.(Q2 * A2,digits=6)

3×2 Matrix{Float64}:
 2.23607  0.0
 0.0      1.0
 0.0      0.0

In [60]:
Q=Q1*Q2

3×3 Matrix{Float64}:
  0.894427   0.0  0.447214
 -0.447214  -0.0  0.894427
  0.0       -1.0  0.0

In [71]:
Qtil = Q[:,1:2]

3×2 Matrix{Float64}:
  0.894427   0.0
 -0.447214  -0.0
  0.0       -1.0

In [110]:
btil=round.(Qtil'*[1;1;1;],digits=6)

2-element Vector{Float64}:
  0.447213
 -1.0

In [74]:
Rtil = [2.23607 0; 0 1;]

2×2 Matrix{Float64}:
 2.23607  0.0
 0.0      1.0

In [76]:
Rtil*x = btil

LoadError: error in method definition: function Base.* must be explicitly imported to be extended

In [85]:
x=[0.2;-1;]

2-element Vector{Float64}:
  0.2
 -1.0

In [90]:
b=[1;1;1;]

3-element Vector{Int64}:
 1
 1
 1

In [91]:
norm(A*x - b)^2

1.8

1.8