In [7]:
using LinearAlgebra

In [8]:
U = [
1/sqrt(5) 2/sqrt(5);
-2*sqrt(5)/5 sqrt(5)/5;
0  0;
]

3×2 Matrix{Float64}:
  0.447214  0.894427
 -0.894427  0.447214
  0.0       0.0

In [9]:
E = [sqrt(10) 0; 0 sqrt(40);]

2×2 Matrix{Float64}:
 3.16228  0.0
 0.0      6.32456

In [10]:
V = [-1/sqrt(2) 1/sqrt(2); 1/sqrt(2) 1/sqrt(2);]

2×2 Matrix{Float64}:
 -0.707107  0.707107
  0.707107  0.707107

In [11]:
V'

2×2 adjoint(::Matrix{Float64}) with eltype Float64:
 -0.707107  0.707107
  0.707107  0.707107

In [12]:
A = round.(U * E * V')

3×2 Matrix{Float64}:
 3.0   5.0
 4.0  -0.0
 0.0   0.0

In [13]:
A =[-2 0; 0 7; 1 0;]

3×2 Matrix{Int64}:
 -2  0
  0  7
  1  0

In [14]:
#achar autovalores
matrix = A' * A


2×2 Matrix{Int64}:
 5   0
 0  49

In [15]:

eigenvalues_matrix = eigen(matrix).values

2-element Vector{Float64}:
  5.0
 49.0

In [16]:
tam_autov = length(eigenvalues_matrix )

2

In [17]:
eigenvectors = eigen(matrix).vectors

2×2 Matrix{Float64}:
 1.0  0.0
 0.0  1.0

In [18]:
eigenvectors[:,1]

2-element Vector{Float64}:
 1.0
 0.0

In [19]:
sigma = []
u = Vector{Vector{Float64}}(undef, tam_autov)
for j in 1: tam_autov
    push!(sigma, sqrt(eigenvalues_matrix[j]))
    u[j] = (1 / sigma[j]) * A * eigenvectors[:, j]
end

In [20]:
U = [u[1] u[2];]

3×2 Matrix{Float64}:
 -0.894427  0.0
  0.0       1.0
  0.447214  0.0

In [21]:
sigma

2-element Vector{Any}:
 2.23606797749979
 7.0

In [22]:
# Inicialize uma matriz de zeros n x n
M = zeros(Float64, length(sigma), length(sigma))

# Preencha os valores da diagonal com os valores do array sigma
for i in 1:length(sigma)
    M[i, i] = sigma[i]
end

In [25]:
A = U * M * eigenvectors'

3×2 Matrix{Float64}:
 -2.0  0.0
  0.0  7.0
  1.0  0.0

In [23]:
u = Vector{Vector{Float64}}(undef, tam_autov)  # Initialize an array of vectors

for j in 1:tam_autov
    u[j] = (1 / sigma[j]) * A * eigenvectors[:, j]
end

